package dev.slash.browser.spike

import dev.slash.browser.sync.SyncCrypto

/**
 * Does Android's sync crypto agree with the desktop's, byte for byte?
 *
 * This is one half of a two-implementation protocol, and a mismatch produces no
 * useful error anywhere. A different scrypt N, a different NFKC decision, or the
 * tag written after the ciphertext instead of before, and every item simply
 * fails to decrypt forever — which presents as "wrong passphrase". The user
 * retypes a correct passphrase repeatedly and concludes sync is broken.
 *
 * So the vectors below were **generated by running the desktop's own
 * `crypto.ts` and `historySync.ts`**, not derived from reading them:
 *
 * ```
 * node scripts/sync-vectors.mjs
 * ```
 *
 * The decisive check is `ciphertextOfHello`: the desktop encrypted it, and this
 * device has to decrypt it. Encrypting on both sides and comparing would prove
 * nothing, because GCM uses a fresh random IV each time — two correct
 * implementations produce different bytes. Only decrypting the other side's
 * output tests interoperability.
 */
object SyncCryptoProbe {

    private const val PASSPHRASE = "correct horse battery staple"
    private const val SALT_HEX = "000102030405060708090a0b0c0d0e0f"
    private const val KEY_HEX = "d7590aca2c9801cf06eeba772a69dc31ce3862591d96522ac4e6bba6ad1f31a5"
    private const val VERIFIER_HEX = "bef0af8f8a2db0a130c74ee3281c47e0"
    private const val CIPHERTEXT =
        "HrabZm7Z1Sb4KU6NrdDOP4jWihkOCVmdKwlz7Die2g/THoKV5j+739a04C4yl6d3Hls="
    private const val PLAINTEXT = "hello from the desktop"
    private const val HISTORY_URL = "https://example.com/a-private-page"
    private const val HISTORY_ID = "1b95b631b6ff41935faca533d9afea729696ac77e50396398dd5f29825ac4c5a"

    // A passphrase whose composed and decomposed forms differ. Without NFKC the
    // same password typed on two platforms derives two different keys.
    private const val UNICODE_PASSPHRASE = "café パス"
    private const val UNICODE_KEY_HEX =
        "c58db03f50bcacd4eaba955df090533eb99fcca014b46bf28eca86fc65ee475a"

    fun run(): ProbeResult {
        val name = "Sync crypto matches the desktop"
        val evidence = LinkedHashMap<String, String>()

        return try {
            val derived = SyncCrypto.deriveKey(PASSPHRASE, SALT_HEX)
            val keyHex = SyncCrypto.bytesToHex(derived.key)
            evidence["scrypt key"] = if (keyHex == KEY_HEX) "matches" else "MISMATCH $keyHex"

            val verifier = SyncCrypto.verifier(derived.key)
            evidence["verifier"] = if (verifier == VERIFIER_HEX) "matches" else "MISMATCH $verifier"
            evidence["verifierMatches()"] =
                SyncCrypto.verifierMatches(derived.key, VERIFIER_HEX).toString()

            val decrypted = SyncCrypto.decrypt(derived.key, CIPHERTEXT)
            evidence["decrypt desktop ciphertext"] =
                if (decrypted == PLAINTEXT) "matches" else "MISMATCH ${decrypted ?: "(null)"}"

            // Round trip in the other direction, so both halves are exercised.
            val ours = SyncCrypto.encrypt(derived.key, PLAINTEXT)
            val roundTrip = SyncCrypto.decrypt(derived.key, ours)
            evidence["our own round trip"] = if (roundTrip == PLAINTEXT) "ok" else "FAILED"

            val historyId = SyncCrypto.historyItemId(derived.key, HISTORY_URL)
            evidence["history id (HMAC)"] =
                if (historyId == HISTORY_ID) "matches" else "MISMATCH $historyId"

            val unicodeKey = SyncCrypto.bytesToHex(
                SyncCrypto.deriveKey(UNICODE_PASSPHRASE, SALT_HEX).key
            )
            evidence["NFKC unicode key"] =
                if (unicodeKey == UNICODE_KEY_HEX) "matches" else "MISMATCH $unicodeKey"

            // A wrong key must return null, not throw and not produce rubbish.
            val wrongKey = SyncCrypto.deriveKey("not the passphrase", SALT_HEX).key
            evidence["wrong key decrypts to"] =
                SyncCrypto.decrypt(wrongKey, CIPHERTEXT)?.let { "TEXT (bad!)" } ?: "null (correct)"

            val failures = evidence.filterValues {
                it.startsWith("MISMATCH") || it == "FAILED" || it == "TEXT (bad!)"
            }.keys

            if (failures.isEmpty()) {
                ProbeResult(
                    name = name,
                    verdict = Verdict.PASS,
                    detail = "Every value matches the desktop, and a ciphertext produced by " +
                        "the desktop decrypted here. The two platforms can read each other.",
                    evidence = evidence
                )
            } else {
                ProbeResult(
                    name = name,
                    verdict = Verdict.FAIL,
                    detail = "Disagrees with the desktop on: ${failures.joinToString(", ")}. " +
                        "Sync between platforms would fail on every item, and would present " +
                        "as a wrong passphrase.",
                    evidence = evidence
                )
            }
        } catch (error: Exception) {
            ProbeResult(
                name = name,
                verdict = Verdict.INCONCLUSIVE,
                detail = "The crypto threw before it could be compared: ${error.message}",
                evidence = evidence
            )
        }
    }
}
